name: network_tools
description: Networking Tools library which can help you discover open ports, devices on subnet and many other things. 
version: 5.0.4
issue_tracker: https://github.com/osociety/network_tools/issues
repository: https://github.com/osociety/network_tools

environment:
  sdk: ">=3.2.0 <4.0.0"

topics:
  - network
  - ping
  - arp
  - port
  - scanner

funding:
  - https://liberapay.com/OpenSociety/donate
  - https://ko-fi.com/fs0c13ty
  
dependencies:
  # A dart csv to list converter.
  csv: ">=5.1.1 <7.0.0"
  # Multi-platform network ping utility.
  dart_ping: ^9.0.1
  # A composable, Future-based library for making HTTP requests.
  http: ^1.2.2
  # Defines the annotations used by json_serializable.
  json_annotation: ^4.9.0
  # Debugging and error logging.
  logging: ^1.3.0
  # Performing mDNS queries (e.g. Bonjour, Avahi).
  multicast_dns: ^0.3.2+7
  # A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.9.1
  # Process run helpers
  process_run: ^1.2.2
  # Yet another NoSQL persistent store database solution for single process io apps.
  sembast: ^3.7.5+2
  # Cross-platform 'dart:io' that works in all platforms.
  universal_io: ^2.2.2
  

dev_dependencies:
  # provides a concrete way of generating files using Dart code
  build_runner: ^2.4.13
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.8.0
  # Set of lint rules for Dart.
  lint: ^2.3.0
  # Writing and running Dart tests.
  test: ^1.25.8